// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV__GJ0nyBN4syhdJbDOhR4Soiw92YKyU',
    appId: '1:48724190243:web:680d1a0b9b95ee1bddfd96',
    messagingSenderId: '48724190243',
    projectId: 'test-e132b',
    authDomain: 'test-e132b.firebaseapp.com',
    storageBucket: 'test-e132b.firebasestorage.app',
    measurementId: 'G-10N2PE9M1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfZZpBvqayT5P-U4MF216dVKjojC2e1UU',
    appId: '1:48724190243:android:71234b99fbae2d3eddfd96',
    messagingSenderId: '48724190243',
    projectId: 'test-e132b',
    storageBucket: 'test-e132b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr-6A6hv-c5awH5Vj0THHVDT3ubP1iTw8',
    appId: '1:48724190243:ios:de7148fe55451e3dddfd96',
    messagingSenderId: '48724190243',
    projectId: 'test-e132b',
    storageBucket: 'test-e132b.firebasestorage.app',
    iosBundleId: 'com.example.newpro1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr-6A6hv-c5awH5Vj0THHVDT3ubP1iTw8',
    appId: '1:48724190243:ios:de7148fe55451e3dddfd96',
    messagingSenderId: '48724190243',
    projectId: 'test-e132b',
    storageBucket: 'test-e132b.firebasestorage.app',
    iosBundleId: 'com.example.newpro1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV__GJ0nyBN4syhdJbDOhR4Soiw92YKyU',
    appId: '1:48724190243:web:189fa5febc513513ddfd96',
    messagingSenderId: '48724190243',
    projectId: 'test-e132b',
    authDomain: 'test-e132b.firebaseapp.com',
    storageBucket: 'test-e132b.firebasestorage.app',
    measurementId: 'G-597NZ1LY6B',
  );
}
